### ISSUE TITLE
Wunsch: Einfügen des GR-Index (aus MOH) in die Fehlermeldung bei der log.txt

### ISSUE THREAD

**Issue by Knecht-ATri** [Achimobil/FS22_MapObjectsHider#3]
Hallo Team,
habe Ingame bei einigen Zäunen die Coli mit dem MOH entfernt, alles super. Nun wollte ich einige Zaunteile unsichtbar mach, ging mit MOH wegen fehlender Coli ja nicht mehr und werden von Bäumen in der Vorschau (Panel) verdeckt. Habe die Objekte dann im GE gelöscht. Nun habe ich Lua-Fehler vom MOH in der log.txt. Ist es möglich, in dieser Fehlermeldung den GE-Index mit anzuzeigen, so dass damit der entsprechende Eintrag in der mapObjectsHider.xml gelöscht werden kann?  Soll ein Vorschlag zum Debugging sein. Für den oben angeführten Vorgang habe ich schon eine andere Lösung.

Thx 4 den Mod und Deinen/Euren Einsatz für die LS-Com. Knecht-ATri

[MOH_LUA .txt](https://github.com/Achimobil/FS22_MapObjectsHider/files/12038821/MOH_LUA.txt)

**Comment by Achimobil** [comment]
Schau ich mir für das nächste Update des Mods an, was da möglich ist.

**Comment by Achimobil** [comment]
Sollte mit dem fix für #4 auch gefixed sein. Da ich das aber nicht nachstellen könnte, kann es sein, muss aber nicht
