### ISSUE TITLE
Nach NF-Marschupdate lad das Spiel nur bis 60%

### ISSUE THREAD

**Issue by 60erjonny** [Achimobil/FS22_MapObjectsHider#4]
Hallo Achim
Wenn du noch weitere Info`s brauchst bitte melden...:-)
[log.txt](https://github.com/Achimobil/FS22_MapObjectsHider/files/12268922/log.txt)
[savegame5.zip](https://github.com/Achimobil/FS22_MapObjectsHider/files/12268931/savegame5.zip)

**Comment by Achimobil** [comment]
@60erjonny kannst du das mit https://github.com/Achimobil/FS22_MapObjectsHider/releases/tag/1.0.1.0_beta_1 testen? 
Ich weiß leider nicht worauf ich da achten muss und ich hab auch viele mods nicht die benötigt werden.

**Comment by 60erjonny** [comment]
Hallo
Nun, das Spiel startet schon mal durch. Aber es werden die Objekte die ich verschwinden lassen habe alle wieder angezeit, bis auf einen Teich. Den habe aber nicht ich unsichtbar gemacht. Der " Teich" ist wie ich vermute, die gewisse Änderung der Karte. Fazit: Der Mod erkennt jetzt zwar die Änderung der Karte, aber die der anderen Objekt noch nicht. Die ganzen Einträge in der xml-Datei sind auch überschrieben worden beim speichern, bis auf den Teich. Ich hoffe es kommt einigermaßen verständlich rüber...:-)
[altmapObjectsHider.zip](https://github.com/Achimobil/FS22_MapObjectsHider/files/12282704/altmapObjectsHider.zip)
[neumapObjectsHider.zip](https://github.com/Achimobil/FS22_MapObjectsHider/files/12282772/neumapObjectsHider.zip)
[log.txt](https://github.com/Achimobil/FS22_MapObjectsHider/files/12282804/log.txt)

**Comment by Achimobil** [comment]
Ich versuche das die tage mal nach zu voll ziehen, wenn ich was nicht verstehe, dann melde ich mich

**Comment by Achimobil** [comment]
Ich kann das alles so leider nicht nachvollziehen. Nur wenn ich es bei mir nachstellen kann am besten mit einem neuen Savegame auf einer Karte die nicht ewig zum laden brauchen und wo mir auch beide Map Versionen zur Verfügung stehen für vergleiche, kann ich da was nachstellen. deshalb muss ich das Ticket aus nicht lösbar schließen bis ich da infos bekomme die ich auch nachstellen kann.

**Comment by Achimobil** [comment]
Hi,

Ich hab einen fix gemacht, vielleicht hilft der auch bei deinem Problem?

https://github.com/Achimobil/FS22_MapObjectsHider/releases/tag/1.0.1.1

**Comment by 60erjonny** [comment]
Habe ihn gestestet, leider nein. Werde aber das Ganze, bei einer neueren Marschversion beobachten...Danke!
